- name: set prompt for the server
  ansible.builtin.shell: set-prompt prometheus

- name: downloading and unzip prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes
    owner: bin

- name: Copy prometheus service file
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

# added in session 27

- name: Copy prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus-{{ version }}.linux-amd64/prometheus/yml

- name: start prometheus service
  ansible.builtin.systemd_service:
    name: prometheus
    state: restarted
    enabled: yes
    daemon-reload: yes

