- name: downloading and unzip app content
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/{{ tool_name }}/releases/download/v2.51.0/prometheus-2.51.0.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes