global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "ec2-node"
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
        filters:
          - name: monitor
            values: ["yes","true"]
